### ISSUE TITLE
Error when creating a new Observation using a phenomenon time and not interval

### ISSUE THREAD

**Issue by LeonardoCasarotto** [FraunhoferIOSB/FROST-Python-Client#18]
Hi, 
We noticed that on the readme there is an error relating to the phenomenon_time, in fact the phenomenon time accepts only a range of time and not a single instant.

e.g.

phenomenon_time='2022-12-19T10:00:00Z/2022-12-19T11:0:0Z',

We are available to make a PR to try to improve the README, thanks!

**Comment by uwzm** [comment]
Dear Leonardo,

thank you for raising this issue. We have just corrected the example code in section "DataArrays" of the README. Instead of

`foi = service.feature_of_interest().find(1)`

we now use

`foi = service.features_of_interest().find(1)`

in plural form, i.e. with an "s" after "feature".
With this correction this example code seems to work for us though. If you make a different experience, could you please post a minimal example code?

Thank you and best regards!
