### ISSUE TITLE
Error: Entity to JSON encoding with location=None

### ISSUE THREAD

**Issue by securedimensions** [FraunhoferIOSB/FROST-Python-Client#30]
# Is this a bug?
When creating a Thing with `locations`, the location property of the Location entity is not rendered into JSON.

## Reproducing the error
1) clone the github
2) create the example as per this Github
```PYTHON
from geojson import Point

import frost_sta_client as fsc

url = "http://localhost:8080/FROST-Server/v1.1"
service = fsc.SensorThingsService(url)
point = Point((-115.81, 37.24))
location = fsc.Location(name="here", description="and there", location=point, encoding_type='application/geo+json')

thing = fsc.Thing(name='new thing',
                  description='I am a thing with a location',
                  properties={'withLocation': True, 'owner': 'IOSB'})
thing.locations = [location]
service.create(thing)
```
3) The error
In line `json_dict = frost_sta_client.utils.transform_entity_to_json_dict(entity)` (line 103 in base.py) renders the location entity 
![grafik](https://github.com/FraunhoferIOSB/FROST-Python-Client/assets/25054643/c5c3c845-eeb5-47fd-a381-c6e1c7be5c09)
into JSON with `location=None`
![grafik](https://github.com/FraunhoferIOSB/FROST-Python-Client/assets/25054643/8cf8f6aa-4200-41bf-9a60-506a0b39bec9)

4) FROST-Server returns error `Property location must be non-NULL`
![grafik](https://github.com/FraunhoferIOSB/FROST-Python-Client/assets/25054643/7e4c62ac-d1a3-4f99-916e-c7013bf44aec)

**Comment by uwzm** [comment]
Hello Andreas!

Thank you for your feedback.

In order to reproduce the problem we appended the line

print(fsc.utils.transform_entity_to_json_dict(thing))

to your example code and got the output

{'@iot.id': 32, 'Locations': [{'description': 'and there', 'encodingType': 'application/geo+json', 'location': {'coordinates': [-115.81, 37.24], 'type': 'Point'}, 'name': 'here'}], 'description': 'I am a thing with a location', 'name': 'new thing', 'properties': {'owner': 'IOSB', 'withLocation': True}}

Here, the point coordinates are included. Is this the situation you are referring to?

In case you query the server for the newly created thing, please keep in mind to include the expand command:

for th in service.things().query().filter("name eq 'new thing'").expand("Locations").list():
    print("JSON: {}".format(fsc.utils.transform_entity_to_json_dict(th)))

If you have got any further questions, feel free to ask.
